three_d_viewer/urls.py
from django.conf import settings
from django.conf.urls import patterns, url
from django.views import generic
from three_d_viewer import views

urlpatterns = patterns(
    '',
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^$', generic.TemplateView.as_view(template_name="three_d_viewer/home.html"), name='home'),
    url(r'^theory/structure/$', views.TheoryTemplateView.as_view(template_name="three_d_viewer/theory/structure.html"), name='theory_structure'),
    url(r'^theory/erb101_structure/$', views.ERB101TheoryTemplateView.as_view(template_name="three_d_viewer/theory/structure.html"), name='erb101_theory_structure'),
    url(r'^theory/bowen/$', views.TheoryTemplateView.as_view(template_name="three_d_viewer/theory/bowen.html"), name='theory_bowen'),
    url(r'^theory/erb101_bowen/$', views.ERB101TheoryTemplateView.as_view(template_name="three_d_viewer/theory/bowen.html"  ), name='erb101_theory_bowen'),
    url(r'^theory/pressure_temp/$', views.TheoryTemplateView.as_view(template_name="three_d_viewer/theory/pressure_temp.html"), name='theory_pt'),
    url(r'^theory/erb101_pressure_temp/$', views.ERB101TheoryTemplateView.as_view(template_name="three_d_viewer/theory/pressure_temp.html"), name='erb101_theory_pt'),
    url(r'^theory/formationdiff/$', views.TheoryTemplateView.as_view(template_name="three_d_viewer/theory/formationdiff.html"), name='theory_fd'),
    url(r'^theory/erb101_formationdiff/$', views.ERB101TheoryTemplateView.as_view(template_name="three_d_viewer/theory/formationdiff.html"), name='erb101_theory_fd'),    
    url(r'^theory/silicates/$', views.TheoryTemplateView.as_view(template_name="three_d_viewer/theory/silicates.html"), name='theory_silicates'),
    url(r'^theory/erb101_silicates/$', views.ERB101TheoryTemplateView.as_view(template_name="three_d_viewer/theory/silicates.html"), name='erb101_theory_silicates'),
    url(r'^theory/classification/$', views.TheoryTemplateView.as_view(template_name="three_d_viewer/theory/classification.html"), name='theory_classification'),
    url(r'^theory/erb101_classification/$', views.ERB101TheoryTemplateView.as_view(template_name="three_d_viewer/theory/classification.html"), name='erb101_theory_classification'),    
    url(r'^theory/crystals/$', views.TheoryTemplateView.as_view(template_name="three_d_viewer/theory/crystals.html"), name='theory_crystals'),
    url(r'^theory/erb101_crystals/$', views.ERB101TheoryTemplateView.as_view(template_name="three_d_viewer/theory/crystals.html"), name='erb101_theory_crystals'),    
    url(r'^minerals_practice/$', views.MineralPracticeView.as_view(template_name="three_d_viewer/minerals_practice.html"), name='minerals_practice'),
    url(r'^minerals/(?P<pk>\d+)/$', views.MineralDetailView.as_view(), name='mineral_detail'),
    url(r'^minerals_selftest/$', generic.TemplateView.as_view(template_name="three_d_viewer/minerals_selftest.html"), name='minerals_selftest'),
    url(r'^rock_practice/$', views.RockPracticeView.as_view(), name='rocks_practice'),
    url(r'^rocks/(?P<pk>\d+)/$', views.RockDetailView.as_view(), name='rock_detail'),
    url(r'^fossil_practice/$', views.FossilPracticeView.as_view(), name='fossil_practice'),
    url(r'^fossils/(?P<pk>\d+)/$', views.FossilDetailView.as_view(), name='fossil_detail'),
    url(r'^glossary/$', views.GlossaryView.as_view(), name='glossary'),
    url(r'^acknowledgements/$', generic.TemplateView.as_view(template_name='three_d_viewer/acknowledgements.html'), name='acknowledgements'),
    url(r'^erb101/$', views.ERB101HomeView.as_view(), name='erb101_home'),
    url(r'^erb101/$', generic.TemplateView.as_view(template_name="three_d_viewer/erb101/home.html"), name='erb101_home'),
    url(r'^erb101_rock_practice/$', views.ERB101RockPracticeView.as_view(), name='erb101_rocks_practice'),
    url(r'^erb101_minerals_practice/$', views.ERB101MineralPracticeView.as_view(), name='erb101_minerals_practice'),
    url(r'^erb101_minerals/(?P<pk>\d+)/$', views.ERB101MineralDetailView.as_view(), name='erb101_mineral_detail'),
    url(r'^erb101_rocks/(?P<pk>\d+)/$', views.ERB101RockDetailView.as_view(), name='erb101_rock_detail'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
)

urls.py
from django.conf.urls import patterns, include, url
from dajaxice.core import dajaxice_config

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'rockviewer.views.home', name='home'),
    # url(r'^rockviewer/', include('rockviewer.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'', include('three_d_viewer.urls', namespace="three_d_viewer")),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

three_d_viewer/views.py
"""
Define the views for the Django MVC
"""

from django import template
from django.views import generic
from itertools import chain
from operator import attrgetter

from three_d_viewer.models import Sample, Category, Mineral, GlossaryEntry
register = template.Library()


class HomeView(generic.ListView):
    """
    Show the home page
    """

    template_name = 'three_d_viewer/home.html'
    model = Sample

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['active_samples'] = Sample.objects.select_subclasses(Mineral).filter(active=True).order_by('name')
        context['parent_categories'] = Category.objects.filter(parent=None). \
            filter(active=True).order_by('name')
        return context

class MineralPracticeView(generic.ListView):
    model = Mineral
    template_name = 'three_d_viewer/minerals_practice.html'

    def get_context_data(self, **kwargs):
        context = super(MineralPracticeView, self).get_context_data(**kwargs)
        cat = Category.objects.get(name='Minerals')
        result = cat.active_samples

        for child in cat.active_children:
            result = chain(result, child.active_samples)

        context['active_samples'] = sorted(result, key=attrgetter('name'))
        context['base_template'] = 'three_d_viewer/base.html'
        return context

class MineralDetailView(generic.DetailView):
    """
    Add extra functionality for mineral details
    """

    model = Mineral
    template_name = 'three_d_viewer/mineral_detail.html'

    parent_categories = Category.objects.filter(parent=None). \
        filter(active=True).order_by("name")

    def get_context_data(self, **kwargs):
        context = super(MineralDetailView, self).get_context_data(**kwargs)
        cat = Category.objects.get(name='Minerals')
        result = cat.active_samples

        for child in cat.active_children:
            result = chain(result, child.active_samples)

        context['active_samples'] = sorted(result, key=attrgetter('name'))
        context['base_template'] = 'three_d_viewer/base.html'
        return context

    def get_object(self, queryset=None):
        object = super(MineralDetailView, self).get_object()
        object.viewed_count += 1
        object.save()
        return object

class RockPracticeView(generic.ListView):
    model = Sample
    template_name = 'three_d_viewer/rock_practice.html'

    parent_categories = Category.objects.filter(parent=None). \
        filter(active=True).order_by("name")


    def get_context_data(self, **kwargs):
        context = super(RockPracticeView, self).get_context_data(**kwargs)
        cat = Category.objects.get(name='Rocks')
        result = cat.active_samples

        for child in cat.active_children:
            result = chain(result, child.active_samples)

        context['active_samples'] = sorted(result, key=attrgetter('name'))
        context['base_template'] = 'three_d_viewer/base.html'
        return context

class RockDetailView(generic.DetailView):
    model = Sample
    template_name = 'three_d_viewer/rock_detail.html'

    parent_categories = Category.objects.filter(parent=None). \
        filter(active=True).order_by("name")


    def get_context_data(self, **kwargs):
        context = super(RockDetailView, self).get_context_data(**kwargs)
        cat = Category.objects.get(name='Rocks')
        result = cat.active_samples

        for child in cat.active_children:
            result = chain(result, child.active_samples)

        context['active_samples'] = sorted(result, key=attrgetter('name'))
        context['base_template'] = 'three_d_viewer/base.html'
        return context

    def get_object(self, queryset=None):
        object = super(RockDetailView, self).get_object()
        object.viewed_count += 1
        object.save()
        return object

class FossilPracticeView(generic.ListView):
    model = Sample
    template_name = 'three_d_viewer/fossil_practice.html'

    parent_categories = Category.objects.filter(parent=None). \
        filter(active=True).order_by("name")


    def get_context_data(self, **kwargs):
        context = super(FossilPracticeView, self).get_context_data(**kwargs)
        cat = Category.objects.get(name='Fossils')
        result = cat.active_samples

        for child in cat.active_children:
            result = chain(result, child.active_samples)

        context['active_samples'] = sorted(result, key=attrgetter('name'))
        context['base_template'] = 'three_d_viewer/base.html'
        return context

class FossilDetailView(generic.DetailView):
    model = Sample
    template_name = 'three_d_viewer/fossil_detail.html'

    parent_categories = Category.objects.filter(parent=None). \
        filter(active=True).order_by("name")


    def get_context_data(self, **kwargs):
        context = super(FossilDetailView, self).get_context_data(**kwargs)
        cat = Category.objects.get(name='Fossils')
        result = cat.active_samples

        for child in cat.active_children:
            result = chain(result, child.active_samples)

        context['active_samples'] = sorted(result, key=attrgetter('name'))
        context['base_template'] = 'three_d_viewer/base.html'
        return context

    def get_object(self, queryset=None):
        object = super(FossilDetailView, self).get_object()
        object.viewed_count += 1
        object.save()
        return object
	
class GlossaryView(generic.ListView):
	model = GlossaryEntry
	template_name = 'three_d_viewer/glossary.html'
	
	def get_context_data(self, **kwargs):
	    context = super(GlossaryView, self).get_context_data(**kwargs)
	    context['entries'] = GlossaryEntry.objects.all().order_by("name")
	    return context
        
class ERB101HomeView(generic.ListView):
    """
    Show the home page
    """

    template_name = 'three_d_viewer/erb101/home.html'
    model = Sample

    def get_context_data(self, **kwargs):
        context = super(ERB101HomeView, self).get_context_data(**kwargs)
        context['active_samples'] = Sample.objects.select_subclasses(Mineral).filter(active=True).filter(erb101_sample=True).order_by('name')
        context['parent_categories'] = Category.objects.filter(parent=None). \
            filter(active=True).order_by('name')
        return context  

class ERB101MineralPracticeView(generic.ListView):
    model = Mineral
    template_name = 'three_d_viewer/erb101/minerals_practice.html'

    def get_context_data(self, **kwargs):
        context = super(ERB101MineralPracticeView, self).get_context_data(**kwargs)
        cat = Category.objects.get(name='Minerals')
        result = cat.active_101_samples

        for child in cat.active_children:
            result = chain(result, child.active_101_samples)

        context['active_samples'] = sorted(result, key=attrgetter('name'))
        context['base_template'] = 'three_d_viewer/erb101/base.html'
        return context
        
class ERB101MineralDetailView(generic.DetailView):
    """
    Add extra functionality for mineral details
    """

    model = Mineral
    template_name = 'three_d_viewer/erb101/mineral_detail.html'

    parent_categories = Category.objects.filter(parent=None). \
        filter(active=True).order_by("name")

    def get_context_data(self, **kwargs):
        context = super(ERB101MineralDetailView, self).get_context_data(**kwargs)
        cat = Category.objects.get(name='Minerals')
        result = cat.active_samples

        for child in cat.active_children:
            result = chain(result, child.active_samples)

        context['active_samples'] = sorted(result, key=attrgetter('name'))
        context['base_template'] = 'three_d_viewer/erb101/base.html'
        return context

    def get_object(self, queryset=None):
        object = super(ERB101MineralDetailView, self).get_object()
        object.viewed_count += 1
        object.save()
        return object     
        
class ERB101RockPracticeView(generic.ListView):
    model = Sample
    template_name = 'three_d_viewer/erb101/rock_practice.html'

    parent_categories = Category.objects.filter(parent=None). \
        filter(active=True).order_by("name")


    def get_context_data(self, **kwargs):
        context = super(ERB101RockPracticeView, self).get_context_data(**kwargs)
        cat = Category.objects.get(name='Rocks')
        result = cat.active_101_samples

        for child in cat.active_children:
            result = chain(result, child.active_101_samples)
        
        context['active_samples'] = sorted(result, key=attrgetter('name'))
        context['base_template'] = 'three_d_viewer/erb101/base.html'
        return context
        
        
class ERB101RockDetailView(generic.DetailView):
    model = Sample
    template_name = 'three_d_viewer/erb101/rock_detail.html'

    parent_categories = Category.objects.filter(parent=None). \
        filter(active=True).order_by("name")


    def get_context_data(self, **kwargs):
        context = super(ERB101RockDetailView, self).get_context_data(**kwargs)
        cat = Category.objects.get(name='Rocks')
        result = cat.active_samples

        for child in cat.active_children:
            result = chain(result, child.active_samples)

        context['active_samples'] = sorted(result, key=attrgetter('name'))
        context['base_template'] = 'three_d_viewer/erb101/base.html'
        return context

    def get_object(self, queryset=None):
        object = super(ERB101RockDetailView, self).get_object()
        object.viewed_count += 1
        object.save()
        return object
        
class TheoryTemplateView(generic.TemplateView):

    def get_context_data(self, **kwargs):
        context = super(TheoryTemplateView, self).get_context_data(**kwargs)
        context['base_template'] = 'three_d_viewer/base.html'
        context['url_extender'] = 'three_d_viewer:'
        context['olivine'] = Mineral.objects.filter(name='Olivine')[0]

three_d_viewer/templates/three_d_viewer/base.html
{% load static %}
{% load dajaxice_templatetags %}

<html>
<head>
<meta charset="UTF-8">
<title>3DVOL - 3D Virtual Object Library</title>

{% block includes %}
<link href="{% static "three_d_viewer/css/styles.css" %}" rel="stylesheet" media="screen" />
<script type="text/javascript" src="{% static "three_d_viewer/js/jquery.min.js" %}"></script>
<script type='text/javascript' src="{% static "three_d_viewer/js/menu_jquery.js" %}"></script>
{% endblock %}
</head>

<body onload={% block loadscript %}""{% endblock %}>
<div id="wrapper">
<div id="container">
	<div id="header">
        <div id="logo">
		<a href="{% url 'three_d_viewer:home' %}"><img src={% static "three_d_viewer/images/logo_main.png" %} class="logoImage"></a>
        </div><!-- CLOSE LOGO !-->
    	<div id="menuContainer">
            <div id='cssmenu'>
            <ul>
               {% block home %}
               <li class='active mainitem'><a href="{% url 'three_d_viewer:home' %}"><span>Home</span></a></li>
               <li class='active mainitem'><a href="{% url 'three_d_viewer:erb101_home' %}"><span>ERB101</span></a></li>
               {% endblock %}
               <li class='has-sub mainitem'><a href='#'><span>Minerals</span></a>
                  <ul>
                     <li class='has-sub'><a><span>Theory</span></a>
                        <ul>
                           {% block theory %}
                           <li><a href="{% url 'three_d_viewer:theory_fd' %}"><span>Formation and differentiation of Earth</span></a></li>
                           <li><a href="{% url 'three_d_viewer:theory_structure' %}"><span>Structure of Earth</span></a></li>
                           <li><a href="{% url 'three_d_viewer:theory_pt' %}"><span>Pressure and temperature</span></a></li>
                           <li><a href="{% url 'three_d_viewer:theory_bowen' %}"><span>Bowen's reaction series</span></a></li>
                           <li><a href="{% url 'three_d_viewer:theory_classification' %}"><span>Classification of minerals</span></a></li>
                           <li><a href="{% url 'three_d_viewer:theory_silicates' %}"><span>Silicates</span></a></li>
                           <li class='last'><a href="{% url 'three_d_viewer:theory_crystals' %}"><span>Crystals</span></a></li>
                           {% endblock %}
                        </ul>
                     </li>
                     {% block mineral_practice %}<li><a href="{% url 'three_d_viewer:minerals_practice' %}"><span>Practice</span></a></li>{% endblock %}
                     <!--<li class='last'><a href="{% url 'three_d_viewer:minerals_selftest' %}"><span>Self Test</span></a></li>!-->
                  </ul>
               </li>
               {% block rock_practice %}<li class="mainitem"><a href="{%  url 'three_d_viewer:rocks_practice' %}"><span>Rocks</span></a></li>{% endblock %}
               {% block fossil_menu %}<li class='last mainitem'><a href="{%  url 'three_d_viewer:fossil_practice' %}"><span>Fossils</span></a></li>{% endblock %}
            </ul>
            </div><!-- CLOSE CSSMENU !-->
    </div><!-- CLOSE MENUCONTAINER !-->
    </div><!-- HEADER !-->
    <div id="content">
        {% block content %}
        {% endblock %}
    </div><!-- CLOSE CONTENT !-->
</div><!-- CLOSE CONTAINER !-->
<div id="push"></div><!-- CLOSE PUSH !-->
</div><!-- CLOSE WRAPPER !-->
<div id="footer">
<ul>
	<li><a href="{% url 'three_d_viewer:glossary' %}">Glossary</a></li>
    <li>&nbsp; - &nbsp;</li>
    <li><a href="{% url 'three_d_viewer:acknowledgements' %}">Acknowledgements</a></li>
</ul>
</div><!-- CLOSE FOOTER !-->
</body>
</html>

three_d_viewer/templates/three_d_viewer/fossil_detail.html
{% extends "three_d_viewer/sample_detail.html" %}

{% block load %}
function load(){
  window.addEventListener('resize', resizeCanvas, false);
  resizeCanvas();

  var sampleFilename = '{{ sample.model_filename|escapejs }}';

  if (sampleFilename.trim() == "")
  {
    document.getElementById("progress").innerHTML = "No model defined!";
    return;
  }

  request = new XMLHttpRequest();
  request.open("GET", '{{ MEDIA_URL }}' + sampleFilename, true);
  request.overrideMimeType("text/plain; charset=x-user-defined");
  request.onreadystatechange = function(){
    if (this.readyState == 3 || this.readyState == 4){
      document.getElementById("progress").innerHTML = "Downloading... "
        + formatNumber(this.responseText.length / 1048576, 2) + " MB";
    }
    if (this.readyState == 4 && (this.status == 200 || this.status == 0) ){
      document.getElementById("progress").innerHTML = "Unpacking...";
      setTimeout(loaded, 1);
    }
  }
  request.send();
}
{% endblock load %}

{%  block menu_header %}Select a Fossil{%  endblock %}

three_d_viewer/templates/three_d_viewer/fossil_practice.html
{% extends "three_d_viewer/sample_practice.html" %}

{%  block menu_header %}Select a Fossil{% endblock %}

three_d_viewer/templates/three_d_viewer/glossary.html
{% extends "three_d_viewer/base.html" %}

{% block content %}
    <div id="pushDownTwo"></div>
    <div id="mainText">
        <p><h3 class="headings">Glossary</h3><br><br>
	<table>
	{% for entry in entries %}
		<tr>
			<td class="term"><p>{{ entry.name }}</p></td>
			<td><p>{{ entry.definition|safe }}</p></td>
		</tr>
	{% endfor %}
	</table>
    </div>
{% endblock %}

three_d_viewer/templates/three_d_viewer/home.html
{% extends "three_d_viewer/base.html" %}

{% block content %}
    <div id="pushDownTwo"></div>
    <div id="mainText">
        <h3 class="headings">Welcome to 3DVOL – Minerals.</h3><br><br>
	<p>
        This website contains a three-dimensional virtual object library of the most important rock-forming minerals making up planet Earth. You will find information on:<br>
	</p>
        <br/>
        <ul class="introList">
          <li><p>Which are the most common minerals on Earth?</p></li>
          <li><p>What are their most important physical and chemical properties?</p></li>
        <li><p>Where in the Earth and under which physical conditions do they form?</p></li>
        <li><p>How can they be identified in hand specimen?</p></li>
        </ul>
<br/>
        <p>A mineral is typically defined as an inorganic solid with a particular chemical composition and a characteristic, periodic atomic structure.
        This characteristic atomic make-up is often reflected in the macroscopic crystalline structure of a mineral.
        The 3D models presented on this website will help you to visualise, study, and memorise these beautiful and often
        complex crystal structures as well as other diagnostic features of minerals.
        <br>
        We hope that you enjoy using 3DVOL.
         </p>
	<br /><br /><br />
	<p>
	DISCLAIMER
	<br /><br />
	This website is a prototype and in statu nascendi. Our development team will continue to add 3D models and associated information 
	and metadata. Various modules do not work yet, for example, the self-practice section. In addition, the website only works with 
	Mozilla Firefox and Google Chrome at the moment. The website can only be accessed from within the QUT network. 
	If you would like to access it from home, you will need to use QUT VPN to do so.
	<br /><br />
	However, we would appreciate if you would have a play with the existing models. We try to evaluate how useful a website 
	like this could be as a complementary teaching tool. Further developments require a lot of man hours and hence funding. 
	If we can demonstrate that you, the user, deem this website interesting and potentially useful we have a good chance to 
	continue our work on 3DVOL. Hence, we kindly ask you to provide your valued feedback. To this end, we set up a short survey, 
	which you can access via this URL: <a href="http://app.gosoapbox.com/">http://app.gosoapbox.com/</a>. The access code is: 3dvol
	<br /><br />
	Alternatively, we are also happy to receive feedback and comments via e-mail. Please, feel free to contact any of the people below.
	<br /><br />
	Thanks a lot and happy exploring,
	<br />
	Your 3DVOL team
	<br /><br />
	Contacts:
	</br><br />
	Christoph Schrank: <a href="mailto:christoph.schrank@qut.edu.au">christoph.schrank@qut.edu.au</a><br />
	Linda Nothdurft: <a href="linda.nothdurft@qut.edu.au">linda.nothdurft@qut.edu.au</a><br />
	Luke Nothdurft: <a href="l.nothdurft@qut.edu.au">l.nothdurft@qut.edu.au</a><br />
	</p>
    </div><!-- CLOSE MAINTEXT !-->
{% endblock %}

three_d_viewer/templates/three_d_viewer/mineral_detail.html
{% extends "three_d_viewer/sample_detail.html" %}

{% block load %}
function load(){
  window.addEventListener('resize', resizeCanvas, false);
  resizeCanvas();

  var sampleFilename = '{{ mineral.model_filename|escapejs }}';

  if (sampleFilename.trim() == "")
  {
    document.getElementById("progress").innerHTML = "No model defined!";
    return;
  }

  request = new XMLHttpRequest();
  request.open("GET", '{{ MEDIA_URL }}' + sampleFilename, true);
  request.overrideMimeType("text/plain; charset=x-user-defined");
  request.onreadystatechange = function(){
    if (this.readyState == 3 || this.readyState == 4){
      document.getElementById("progress").innerHTML = "Downloading... "
        + formatNumber(this.responseText.length / 1048576, 2) + " MB";
    }
    if (this.readyState == 4 && (this.status == 200 || this.status == 0) ){
      document.getElementById("progress").innerHTML = "Unpacking...";
      setTimeout(loaded, 1);
    }
  }
  request.send();
}
{% endblock load %}

{%  block menu_header %}Select a Mineral{%  endblock %}

{% block sample_detail %}
    <div id="mineralContainer">
        <div id="mineralOne">
            <h1 class="subHeadings">{{  mineral.name }}</h1>
            <h2 class="theoryHeadings">Physical properties</h2>
            <table class="theoryHeadings">
                  <tr>
                    <td><p>Chemical Formula:</p></td>
                    <td><p>{{ mineral.chemical_formula|safe }}</p></td>
                  </tr>
                  <tr>
                    <td><p>Hardness:</p></td>
                    <td><p>{{ mineral.hardness }}</p></td>
                  </tr>
                  <tr>
                    <td><p>Specific Gravity:</p></td>
                    <td><p>{{ mineral.specific_gravity }}</p></td>
                  </tr>
                  <tr>
                    <td><p>Cleavage/Fracture:</p></td>
                    <td><p>{{ mineral.cleavage_fracture }}</p></td>
                  </tr>
                  <tr>
                    <td><p>Lustre:</p></td>
                    <td><p>{{ mineral.lustre }}</p></td>
                  </tr>
                  <tr>
                    <td><p>Colour:</p></td>
                    <td><p>{{ mineral.colour }}</p></td>
                  </tr>
                  <tr>
                    <td><p>Streak:</p></td>
                    <td><p>{{ mineral.streak }}</p></td>
                  </tr>
                  <tr>
                    <td><p>Habit:</p></td>
                    <td><p>{{ mineral.habit }}</p></td>
                  </tr>
                  <tr>
                    <td><p>Crystallography:</p></td>
                    <td><p>{{ mineral.crystallography }}</p></td>
                  </tr>
            </table>
            <h2 class="theoryHeadings">Diagnostic features</h2>
            <p>{{ mineral.identifying_features }}</p>
            <h2 class="theoryHeadings">Geological significance</h2>
            <p>{{ mineral.occurance }}</p>
        </div>
    </div>
{% endblock %}